set(SRC_FILES
    App.cpp
    Block.cpp
    BrickBlock.cpp
    Camera.cpp
    Character.cpp
    Enemy.cpp
    FlagBlock.cpp
    GameManager.cpp
    Goomba.cpp
    GroundBlock.cpp
    HUD.cpp
    Item.cpp
    Koopa.cpp
    LevelLoader.cpp
    MushroomItem.cpp
    CoinItem.cpp
    FireFlowerItem.cpp
    Fireball.cpp
    PipeBlock.cpp
    Player.cpp
    QuestionBlock.cpp
    WallBlock.cpp
)

set(INCLUDE_FILES
    App.hpp
    AssetPath.hpp
    Block.hpp
    BrickBlock.hpp
    Camera.hpp
    Character.hpp
    Enemy.hpp
    FlagBlock.hpp
    Item.hpp
    MushroomItem.hpp
    CoinItem.hpp
    FireFlowerItem.hpp
    Fireball.hpp
    GameConstants.hpp
    GameManager.hpp
    Goomba.hpp
    GroundBlock.hpp
    HUD.hpp
    Koopa.hpp
    LevelData.hpp
    LevelLoader.hpp
    PipeBlock.hpp
    Player.hpp
    QuestionBlock.hpp
    WallBlock.hpp
)

set(TEST_FILES
)
