set(SRC_FILES
    App.cpp
    Block.cpp
    BrickBlock.cpp
    BrickDebris.cpp
    Camera.cpp
    Character.cpp
    Enemy.cpp
    FlagBlock.cpp
    GameManager.cpp
    GameSession.cpp
    Goomba.cpp
    GroundBlock.cpp
    HUD.cpp
    Item.cpp
    Koopa.cpp
    LevelLoader.cpp
    MushroomItem.cpp
    MovingPlatformBlock.cpp
    CoinItem.cpp
    FireFlowerItem.cpp
    Fireball.cpp
    PipeBlock.cpp
    PiranhaPlant.cpp
    Player.cpp
    QuestionBlock.cpp
    TreePlatformBlock.cpp
    WallBlock.cpp
)

set(INCLUDE_FILES
    App.hpp
    AssetPath.hpp
    Block.hpp
    BrickBlock.hpp
    BrickDebris.hpp
    Camera.hpp
    Character.hpp
    Enemy.hpp
    FlagBlock.hpp
    Item.hpp
    MushroomItem.hpp
    CoinItem.hpp
    FireFlowerItem.hpp
    Fireball.hpp
    GameConstants.hpp
    GameManager.hpp
    GameSession.hpp
    Goomba.hpp
    GroundBlock.hpp
    HUD.hpp
    Koopa.hpp
    LevelData.hpp
    LevelLoader.hpp
    PipeBlock.hpp
    MovingPlatformBlock.hpp
    PiranhaPlant.hpp
    Player.hpp
    QuestionBlock.hpp
    TreePlatformBlock.hpp
    WallBlock.hpp
)

set(TEST_FILES
)
